apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
      - name: maven-app
        image: adexxy/spring-app:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1 
kind: Service 
metadata:
  name: maven-app
spec:
  selector:
    type: NodePort
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
